expiration_time: 120.0
# Weights - relative position leader (3d), relative position follower (3d), velocity error (3d), att error(3d)
W: [10, 10, 10, 0.05, 0.05, 0.05, 10, 10, 10, 10, 10, 10, 5, 5, 5, 50, 50, 50]
WN: [10, 10, 10, 0.05, 0.05, 0.05, 10, 10, 10, 10, 10, 10]
WN_gain: 200
# Test Targets
bearings:
  l: [1.0, 0.0, 0.0]
  f1: [-1.0, 0.0, 0.0]
qd: [1, 0, 0, 0]