/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadcopter_rk4_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

/* quadcopter_rk4_expl_vde_adj:(i0[12],i1[12],i2[4],i3[])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+12, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+55, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 12, w1);
  /* #2: {@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13} = vertsplit(@1) */
  w2 = w1[0];
  w3 = w1[1];
  w4 = w1[2];
  w5 = w1[3];
  w6 = w1[4];
  w7 = w1[5];
  w8 = w1[6];
  w9 = w1[7];
  w10 = w1[8];
  w11 = w1[9];
  w12 = w1[10];
  w13 = w1[11];
  /* #3: @14 = -0.0111366 */
  w14 = -1.1136600000000003e-02;
  /* #4: @1 = input[0][0] */
  casadi_copy(arg[0], 12, w1);
  /* #5: @15 = @1[7] */
  for (rr=(&w15), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #6: @16 = 10.2354 */
  w16 = 1.0235414534288639e+01;
  /* #7: @16 = (@16*@10) */
  w16 *= w10;
  /* #8: @10 = (@15*@16) */
  w10  = (w15*w16);
  /* #9: @10 = (@14*@10) */
  w10  = (w14*w10);
  /* #10: @10 = (@11+@10) */
  w10  = (w11+w10);
  /* #11: @17 = 0.0629437 */
  w17 = 6.2943699999999991e-02;
  /* #12: @18 = @1[8] */
  for (rr=(&w18), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #13: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #14: @20 = 21.7899 */
  w20 = 2.1789862919972371e+01;
  /* #15: @20 = (@20*@9) */
  w20 *= w9;
  /* #16: @19 = (@19*@20) */
  w19 *= w20;
  /* #17: @10 = (@10+@19) */
  w10 += w19;
  /* #18: (@0[6] += @10) */
  for (rr=w0+6, ss=(&w10); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #19: @10 = @1[9] */
  for (rr=(&w10), ss=w1+9; ss!=w1+10; ss+=1) *rr++ = *ss;
  /* #20: @19 = cos(@10) */
  w19 = cos( w10 );
  /* #21: @9 = @1[10] */
  for (rr=(&w9), ss=w1+10; ss!=w1+11; ss+=1) *rr++ = *ss;
  /* #22: @21 = cos(@9) */
  w21 = cos( w9 );
  /* #23: @22 = (@13/@21) */
  w22  = (w13/w21);
  /* #24: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #25: @24 = sin(@10) */
  w24 = sin( w10 );
  /* #26: @24 = (@24*@12) */
  w24 *= w12;
  /* #27: @23 = (@23-@24) */
  w23 -= w24;
  /* #28: @24 = cos(@10) */
  w24 = cos( w10 );
  /* #29: @25 = tan(@9) */
  w25 = tan( w9 );
  /* #30: @25 = (@25*@11) */
  w25 *= w11;
  /* #31: @26 = (@24*@25) */
  w26  = (w24*w25);
  /* #32: @23 = (@23+@26) */
  w23 += w26;
  /* #33: @26 = @1[6] */
  for (rr=(&w26), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #34: @27 = (@26*@20) */
  w27  = (w26*w20);
  /* #35: @17 = (@17*@27) */
  w17 *= w27;
  /* #36: @23 = (@23+@17) */
  w23 += w17;
  /* #37: @17 = -0.0518071 */
  w17 = -5.1807099999999995e-02;
  /* #38: @27 = (@17*@15) */
  w27  = (w17*w15);
  /* #39: @28 = 28.7718 */
  w28 = 2.8771762241665542e+01;
  /* #40: @28 = (@28*@8) */
  w28 *= w8;
  /* #41: @27 = (@27*@28) */
  w27 *= w28;
  /* #42: @23 = (@23+@27) */
  w23 += w27;
  /* #43: (@0[8] += @23) */
  for (rr=w0+8, ss=(&w23); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #44: @23 = sin(@10) */
  w23 = sin( w10 );
  /* #45: @27 = cos(@9) */
  w27 = cos( w9 );
  /* #46: @8 = (@13/@27) */
  w8  = (w13/w27);
  /* #47: @29 = (@23*@8) */
  w29  = (w23*w8);
  /* #48: @30 = cos(@10) */
  w30 = cos( w10 );
  /* #49: @30 = (@30*@12) */
  w30 *= w12;
  /* #50: @29 = (@29+@30) */
  w29 += w30;
  /* #51: @30 = sin(@10) */
  w30 = sin( w10 );
  /* #52: @31 = tan(@9) */
  w31 = tan( w9 );
  /* #53: @31 = (@31*@11) */
  w31 *= w11;
  /* #54: @32 = (@30*@31) */
  w32  = (w30*w31);
  /* #55: @29 = (@29+@32) */
  w29 += w32;
  /* #56: @14 = (@14*@26) */
  w14 *= w26;
  /* #57: @14 = (@14*@16) */
  w14 *= w16;
  /* #58: @29 = (@29+@14) */
  w29 += w14;
  /* #59: @14 = (@18*@28) */
  w14  = (w18*w28);
  /* #60: @17 = (@17*@14) */
  w17 *= w14;
  /* #61: @29 = (@29+@17) */
  w29 += w17;
  /* #62: (@0[7] += @29) */
  for (rr=w0+7, ss=(&w29); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #63: @29 = @1[11] */
  for (rr=(&w29), ss=w1+11; ss!=w1+12; ss+=1) *rr++ = *ss;
  /* #64: @17 = sin(@29) */
  w17 = sin( w29 );
  /* #65: @14 = sin(@10) */
  w14 = sin( w10 );
  /* #66: @33 = input[2][0] */
  casadi_copy(arg[2], 4, w33);
  /* #67: @26 = @33[0] */
  for (rr=(&w26), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #68: @32 = 0.930233 */
  w32 = 9.3023255813953487e-01;
  /* #69: @32 = (@32*@6) */
  w32 *= w6;
  /* #70: @6 = (@26*@32) */
  w6  = (w26*w32);
  /* #71: @34 = (@14*@6) */
  w34  = (w14*w6);
  /* #72: @17 = (@17*@34) */
  w17 *= w34;
  /* #73: @34 = cos(@29) */
  w34 = cos( w29 );
  /* #74: @35 = cos(@10) */
  w35 = cos( w10 );
  /* #75: @36 = sin(@9) */
  w36 = sin( w9 );
  /* #76: @37 = (@35*@36) */
  w37  = (w35*w36);
  /* #77: @38 = (@37*@6) */
  w38  = (w37*w6);
  /* #78: @34 = (@34*@38) */
  w34 *= w38;
  /* #79: @17 = (@17+@34) */
  w17 += w34;
  /* #80: @34 = cos(@29) */
  w34 = cos( w29 );
  /* #81: @38 = sin(@10) */
  w38 = sin( w10 );
  /* #82: @39 = 0.930233 */
  w39 = 9.3023255813953487e-01;
  /* #83: @39 = (@39*@5) */
  w39 *= w5;
  /* #84: @5 = (@26*@39) */
  w5  = (w26*w39);
  /* #85: @40 = (@38*@5) */
  w40  = (w38*w5);
  /* #86: @34 = (@34*@40) */
  w34 *= w40;
  /* #87: @17 = (@17+@34) */
  w17 += w34;
  /* #88: @34 = sin(@29) */
  w34 = sin( w29 );
  /* #89: @40 = cos(@10) */
  w40 = cos( w10 );
  /* #90: @41 = sin(@9) */
  w41 = sin( w9 );
  /* #91: @42 = (@40*@41) */
  w42  = (w40*w41);
  /* #92: @43 = (@42*@5) */
  w43  = (w42*w5);
  /* #93: @34 = (@34*@43) */
  w34 *= w43;
  /* #94: @17 = (@17-@34) */
  w17 -= w34;
  /* #95: (@0[11] += @17) */
  for (rr=w0+11, ss=(&w17); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #96: @17 = sin(@9) */
  w17 = sin( w9 );
  /* #97: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #98: @19 = (@19/@21) */
  w19 /= w21;
  /* #99: @19 = (@19/@21) */
  w19 /= w21;
  /* #100: @19 = (@19*@13) */
  w19 *= w13;
  /* #101: @17 = (@17*@19) */
  w17 *= w19;
  /* #102: @19 = sin(@9) */
  w19 = sin( w9 );
  /* #103: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #104: @23 = (@23/@27) */
  w23 /= w27;
  /* #105: @23 = (@23/@27) */
  w23 /= w27;
  /* #106: @23 = (@23*@13) */
  w23 *= w13;
  /* #107: @19 = (@19*@23) */
  w19 *= w23;
  /* #108: @17 = (@17+@19) */
  w17 += w19;
  /* #109: @24 = (@18*@24) */
  w24  = (w18*w24);
  /* #110: @24 = (@24*@11) */
  w24 *= w11;
  /* #111: @19 = cos(@9) */
  w19 = cos( w9 );
  /* #112: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #113: @24 = (@24/@19) */
  w24 /= w19;
  /* #114: @17 = (@17+@24) */
  w17 += w24;
  /* #115: @30 = (@15*@30) */
  w30  = (w15*w30);
  /* #116: @30 = (@30*@11) */
  w30 *= w11;
  /* #117: @11 = cos(@9) */
  w11 = cos( w9 );
  /* #118: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #119: @30 = (@30/@11) */
  w30 /= w11;
  /* #120: @17 = (@17+@30) */
  w17 += w30;
  /* #121: @30 = sin(@9) */
  w30 = sin( w9 );
  /* #122: @11 = cos(@10) */
  w11 = cos( w10 );
  /* #123: @24 = 0.930233 */
  w24 = 9.3023255813953487e-01;
  /* #124: @24 = (@24*@7) */
  w24 *= w7;
  /* #125: @26 = (@26*@24) */
  w26 *= w24;
  /* #126: @7 = (@11*@26) */
  w7  = (w11*w26);
  /* #127: @30 = (@30*@7) */
  w30 *= w7;
  /* #128: @17 = (@17-@30) */
  w17 -= w30;
  /* #129: @30 = cos(@9) */
  w30 = cos( w9 );
  /* #130: @7 = sin(@29) */
  w7 = sin( w29 );
  /* #131: @19 = (@7*@6) */
  w19  = (w7*w6);
  /* #132: @35 = (@35*@19) */
  w35 *= w19;
  /* #133: @30 = (@30*@35) */
  w30 *= w35;
  /* #134: @17 = (@17+@30) */
  w17 += w30;
  /* #135: @30 = cos(@9) */
  w30 = cos( w9 );
  /* #136: @35 = cos(@29) */
  w35 = cos( w29 );
  /* #137: @23 = (@35*@5) */
  w23  = (w35*w5);
  /* #138: @40 = (@40*@23) */
  w40 *= w23;
  /* #139: @30 = (@30*@40) */
  w30 *= w40;
  /* #140: @17 = (@17+@30) */
  w17 += w30;
  /* #141: (@0[10] += @17) */
  for (rr=w0+10, ss=(&w17); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #142: @17 = cos(@10) */
  w17 = cos( w10 );
  /* #143: @8 = (@15*@8) */
  w8  = (w15*w8);
  /* #144: @17 = (@17*@8) */
  w17 *= w8;
  /* #145: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #146: @22 = (@18*@22) */
  w22  = (w18*w22);
  /* #147: @8 = (@8*@22) */
  w8 *= w22;
  /* #148: @17 = (@17-@8) */
  w17 -= w8;
  /* #149: @8 = cos(@10) */
  w8 = cos( w10 );
  /* #150: @22 = (@18*@12) */
  w22  = (w18*w12);
  /* #151: @8 = (@8*@22) */
  w8 *= w22;
  /* #152: @17 = (@17-@8) */
  w17 -= w8;
  /* #153: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #154: @12 = (@15*@12) */
  w12  = (w15*w12);
  /* #155: @8 = (@8*@12) */
  w8 *= w12;
  /* #156: @17 = (@17-@8) */
  w17 -= w8;
  /* #157: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #158: @18 = (@18*@25) */
  w18 *= w25;
  /* #159: @8 = (@8*@18) */
  w8 *= w18;
  /* #160: @17 = (@17-@8) */
  w17 -= w8;
  /* #161: @8 = cos(@10) */
  w8 = cos( w10 );
  /* #162: @15 = (@15*@31) */
  w15 *= w31;
  /* #163: @8 = (@8*@15) */
  w8 *= w15;
  /* #164: @17 = (@17+@8) */
  w17 += w8;
  /* #165: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #166: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #167: @26 = (@9*@26) */
  w26  = (w9*w26);
  /* #168: @8 = (@8*@26) */
  w8 *= w26;
  /* #169: @17 = (@17-@8) */
  w17 -= w8;
  /* #170: @8 = cos(@10) */
  w8 = cos( w10 );
  /* #171: @26 = cos(@29) */
  w26 = cos( w29 );
  /* #172: @6 = (@26*@6) */
  w6  = (w26*w6);
  /* #173: @8 = (@8*@6) */
  w8 *= w6;
  /* #174: @17 = (@17-@8) */
  w17 -= w8;
  /* #175: @8 = sin(@10) */
  w8 = sin( w10 );
  /* #176: @36 = (@36*@19) */
  w36 *= w19;
  /* #177: @8 = (@8*@36) */
  w8 *= w36;
  /* #178: @17 = (@17-@8) */
  w17 -= w8;
  /* #179: @8 = cos(@10) */
  w8 = cos( w10 );
  /* #180: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #181: @5 = (@29*@5) */
  w5  = (w29*w5);
  /* #182: @8 = (@8*@5) */
  w8 *= w5;
  /* #183: @17 = (@17+@8) */
  w17 += w8;
  /* #184: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #185: @41 = (@41*@23) */
  w41 *= w23;
  /* #186: @10 = (@10*@41) */
  w10 *= w41;
  /* #187: @17 = (@17-@10) */
  w17 -= w10;
  /* #188: (@0[9] += @17) */
  for (rr=w0+9, ss=(&w17); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #189: (@0[5] += @4) */
  for (rr=w0+5, ss=(&w4); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #190: (@0[4] += @3) */
  for (rr=w0+4, ss=(&w3); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #191: (@0[3] += @2) */
  for (rr=w0+3, ss=(&w2); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #192: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #193: @33 = zeros(4x1) */
  casadi_clear(w33, 4);
  /* #194: (@33[3] += @16) */
  for (rr=w33+3, ss=(&w16); rr!=w33+4; rr+=1) *rr += *ss++;
  /* #195: (@33[2] += @20) */
  for (rr=w33+2, ss=(&w20); rr!=w33+3; rr+=1) *rr += *ss++;
  /* #196: (@33[1] += @28) */
  for (rr=w33+1, ss=(&w28); rr!=w33+2; rr+=1) *rr += *ss++;
  /* #197: @11 = (@11*@9) */
  w11 *= w9;
  /* #198: @11 = (@11*@24) */
  w11 *= w24;
  /* #199: @37 = (@37*@7) */
  w37 *= w7;
  /* #200: @14 = (@14*@26) */
  w14 *= w26;
  /* #201: @37 = (@37-@14) */
  w37 -= w14;
  /* #202: @37 = (@37*@32) */
  w37 *= w32;
  /* #203: @11 = (@11+@37) */
  w11 += w37;
  /* #204: @42 = (@42*@35) */
  w42 *= w35;
  /* #205: @38 = (@38*@29) */
  w38 *= w29;
  /* #206: @42 = (@42+@38) */
  w42 += w38;
  /* #207: @42 = (@42*@39) */
  w42 *= w39;
  /* #208: @11 = (@11+@42) */
  w11 += w42;
  /* #209: (@33[0] += @11) */
  for (rr=w33+0, ss=(&w11); rr!=w33+1; rr+=1) *rr += *ss++;
  /* #210: output[0][1] = @33 */
  if (res[0]) casadi_copy(w33, 4, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadcopter_rk4_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadcopter_rk4_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadcopter_rk4_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadcopter_rk4_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadcopter_rk4_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadcopter_rk4_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadcopter_rk4_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 69;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
