/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadcopter_rk4_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* quadcopter_rk4_expl_ode_fun:(i0[12],i1[4],i2[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, *w7=w+18, w8;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 12, w0);
  /* #1: @1 = @0[3] */
  for (rr=(&w1), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[4] */
  for (rr=(&w1), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #7: @1 = @0[9] */
  for (rr=(&w1), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #8: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #9: @3 = @0[10] */
  for (rr=(&w3), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #10: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #11: @2 = (@2*@4) */
  w2 *= w4;
  /* #12: @4 = @0[11] */
  for (rr=(&w4), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #13: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #14: @2 = (@2*@5) */
  w2 *= w5;
  /* #15: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #16: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #17: @5 = (@5*@6) */
  w5 *= w6;
  /* #18: @2 = (@2+@5) */
  w2 += w5;
  /* #19: @7 = input[1][0] */
  casadi_copy(arg[1], 4, w7);
  /* #20: @5 = @7[0] */
  for (rr=(&w5), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  /* #21: @2 = (@2*@5) */
  w2 *= w5;
  /* #22: @6 = 1.075 */
  w6 = 1.0750000000000000e+00;
  /* #23: @2 = (@2/@6) */
  w2 /= w6;
  /* #24: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #25: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #26: @6 = sin(@3) */
  w6 = sin( w3 );
  /* #27: @2 = (@2*@6) */
  w2 *= w6;
  /* #28: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #29: @2 = (@2*@6) */
  w2 *= w6;
  /* #30: @6 = sin(@1) */
  w6 = sin( w1 );
  /* #31: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #32: @6 = (@6*@4) */
  w6 *= w4;
  /* #33: @2 = (@2-@6) */
  w2 -= w6;
  /* #34: @2 = (@2*@5) */
  w2 *= w5;
  /* #35: @6 = 1.075 */
  w6 = 1.0750000000000000e+00;
  /* #36: @2 = (@2/@6) */
  w2 /= w6;
  /* #37: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #38: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #39: @6 = cos(@3) */
  w6 = cos( w3 );
  /* #40: @2 = (@2*@6) */
  w2 *= w6;
  /* #41: @2 = (@2*@5) */
  w2 *= w5;
  /* #42: @5 = 1.075 */
  w5 = 1.0750000000000000e+00;
  /* #43: @2 = (@2/@5) */
  w2 /= w5;
  /* #44: @5 = 9.8066 */
  w5 = 9.8065999999999995e+00;
  /* #45: @2 = (@2-@5) */
  w2 -= w5;
  /* #46: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #47: @2 = -0.0518071 */
  w2 = -5.1807099999999995e-02;
  /* #48: @5 = @0[7] */
  for (rr=(&w5), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #49: @2 = (@2*@5) */
  w2 *= w5;
  /* #50: @6 = @0[8] */
  for (rr=(&w6), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #51: @2 = (@2*@6) */
  w2 *= w6;
  /* #52: @4 = @7[1] */
  for (rr=(&w4), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  /* #53: @2 = (@2+@4) */
  w2 += w4;
  /* #54: @4 = 0.0347563 */
  w4 = 3.4756299999999997e-02;
  /* #55: @2 = (@2/@4) */
  w2 /= w4;
  /* #56: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  /* #57: @2 = 0.0629437 */
  w2 = 6.2943699999999991e-02;
  /* #58: @2 = (@2*@6) */
  w2 *= w6;
  /* #59: @4 = @0[6] */
  for (rr=(&w4), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #60: @2 = (@2*@4) */
  w2 *= w4;
  /* #61: @8 = @7[2] */
  for (rr=(&w8), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  /* #62: @2 = (@2+@8) */
  w2 += w8;
  /* #63: @8 = 0.0458929 */
  w8 = 4.5892900000000000e-02;
  /* #64: @2 = (@2/@8) */
  w2 /= w8;
  /* #65: output[0][7] = @2 */
  if (res[0]) res[0][7] = w2;
  /* #66: @2 = -0.0111366 */
  w2 = -1.1136600000000003e-02;
  /* #67: @2 = (@2*@4) */
  w2 *= w4;
  /* #68: @2 = (@2*@5) */
  w2 *= w5;
  /* #69: @8 = @7[3] */
  for (rr=(&w8), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #70: @2 = (@2+@8) */
  w2 += w8;
  /* #71: @8 = 0.0977 */
  w8 = 9.7699999999999995e-02;
  /* #72: @2 = (@2/@8) */
  w2 /= w8;
  /* #73: output[0][8] = @2 */
  if (res[0]) res[0][8] = w2;
  /* #74: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #75: @2 = (@5*@2) */
  w2  = (w5*w2);
  /* #76: @8 = tan(@3) */
  w8 = tan( w3 );
  /* #77: @2 = (@2*@8) */
  w2 *= w8;
  /* #78: @4 = (@4+@2) */
  w4 += w2;
  /* #79: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #80: @2 = (@6*@2) */
  w2  = (w6*w2);
  /* #81: @8 = tan(@3) */
  w8 = tan( w3 );
  /* #82: @2 = (@2*@8) */
  w2 *= w8;
  /* #83: @4 = (@4+@2) */
  w4 += w2;
  /* #84: output[0][9] = @4 */
  if (res[0]) res[0][9] = w4;
  /* #85: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #86: @4 = (@5*@4) */
  w4  = (w5*w4);
  /* #87: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #88: @2 = (@6*@2) */
  w2  = (w6*w2);
  /* #89: @4 = (@4-@2) */
  w4 -= w2;
  /* #90: output[0][10] = @4 */
  if (res[0]) res[0][10] = w4;
  /* #91: @4 = sin(@1) */
  w4 = sin( w1 );
  /* #92: @5 = (@5*@4) */
  w5 *= w4;
  /* #93: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #94: @5 = (@5/@4) */
  w5 /= w4;
  /* #95: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #96: @6 = (@6*@1) */
  w6 *= w1;
  /* #97: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #98: @6 = (@6/@3) */
  w6 /= w3;
  /* #99: @5 = (@5+@6) */
  w5 += w6;
  /* #100: output[0][11] = @5 */
  if (res[0]) res[0][11] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadcopter_rk4_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadcopter_rk4_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quadcopter_rk4_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadcopter_rk4_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadcopter_rk4_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadcopter_rk4_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadcopter_rk4_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadcopter_rk4_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadcopter_rk4_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 23;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
